### ISSUE TITLE
Remove -moz specific text highlighting

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#141]
Autoprefixer catches it, so it's rendering out twice.

``` css
/**
 * Highlighting colors
 */
::-moz-selection {
  color: #ffffff;
  background: #0088cc;
}
::selection {
  color: #ffffff;
  background: #0088cc;
}

::-moz-selection {
  color: #ffffff;
  background: #0088cc;
}
```
