### ISSUE TITLE
Grid update

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#161]
Two options:
1. Breakpoint specific grids. Example:
   
   ``` css
   .grid-fourth {
     @media (min-width: $bp-small) {
        &-bp-small {
           width: 25%;
        }
     }
     ...
   }
   
   .grid-third {
     @media (min-width: $bp-medium) {
        &-bp-medium {
           width: 33.333333%;
        }
     }
     ...
   }
   ```
   
   Renders out as:
   
   ``` css
   @media (min-width: 20em) {
       .grid-fourth-bp-small {
           width: 25%;
       }
   }
   @media (min-width: 30em) {
       .grid-fourth-bp-medium {
           width: 25%;
       }
   }
   ...
   ```
2. Component-based grids. Example:
   
   ``` css
   .module-dogs {
       @media (min-width: $bp-small) {
           width: 50%;
       }
       @media (min-width: $bp-medium) {
           width: 33.33333%;
       }
   }
   ```

**Food for thought:**
- [About HTML Semantics and Front-End Architecture](http://nicolasgallagher.com/about-html-semantics-front-end-architecture/)
- Ethan Marcotte's slides (ex. `.doc-cell` and `:nth` selector float clears)
