### ISSUE TITLE
Shift around styling for .icon class in svgs.scss to avoid over-specificity

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#178]
``` scss
/**
 * Hide icons by default to prevent blank spaces in unsupported browsers
 */
.icon {
    display: inline-block;
    fill: currentColor;
    height: 0;
    width: 0;
}

/**
 * Display icons when browser supports SVG.
 * Inherit height, width, and color.
 */
.svg .icon {
    height: 1em;
    width: 1em;
}
```
