### ISSUE TITLE
Create sticky element script

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#189]
Dynamic based on breakpoints

```js
// obj
target: '.main',
stickyClass: 'toc-sticky',
stickyTargetClass: 'wrap-sticky',

// vars
target = document.querySelector( settings.target );
toc = insertNav( nav, target, settings.insertAfter );
dist = getElemDistance( toc );

// listeners
document.removeEventListener('scroll', eventThrottler, false);
document.removeEventListener('resize', eventThrottler, false);

// event
var eventHandler = function (event) {

	if ( event && event.type && event.type === 'scroll' ) {
		if ( !settings.stickyClass ) return;
		var pos = root.pageYOffset;
		if ( dist - pos <= 0 ) {
			toc.classList.add( settings.stickyClass );
			target.classList.add( settings.stickyTargetClass );
			return;
		}
		toc.classList.remove( settings.stickyClass );
		target.classList.remove( settings.stickyTargetClass );
	}

	if ( event && event.type && event.type === 'resize' ) {
		dist = getElemDistance( toc );
	}

};
```

```css
@media (min-width: 40em) {
  .toc-sticky {
    position: fixed;
    top: 0;
  }

  .wrap-sticky {
    margin-left: 25%;
  }
}
```
