### ISSUE TITLE
Add styling for abbr element

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#190]
``` scss
/**
 * Address styling not present in IE 8/9/10/11, Safari, and Chrome.
 */
abbr[title] {
    border-bottom: 1px dotted;
    cursor: help;
}
```
