### ISSUE TITLE
Add tabindex a11y styling fix

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#258]
```css
/**
 * @workaround Remove focus from <main> element when using tabindex="-1" hack for skipnav link
 * @link https://code.google.com/p/chromium/issues/detail?id=37721
 */
.tabindex:focus {
	outline: none;
}
```
