### ISSUE TITLE
add base normalization for <table> element

### ISSUE THREAD

**Issue by marcop135** [cferdinandi/kraken#26]
I would like to see base table normalization by default in this way:

``` css
table {
  max-width: 100%;
  border-collapse: collapse;
}
```
