### ISSUE TITLE
Fix unstyled/inline list accessibility

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#277]
Via [Scott O'Hara](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html):

```scss
/**
 * @bugfix Prevent webkit from removing list semantics
 * 1. Add a non-breaking space
 * 2. Make sure it doesn't mess up the DOM flow
 */
.list-unstyled,
.list-inline {
	li:before {
		content: "\200B"; /* 1 */
		position: absolute; /* 2 */
	}
}
```
