### ISSUE TITLE
Updated grid structure for more control (see PAWS New England project)

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#89]
**_config.scss**

``` scss
// Grid
$grid-margins: 1.4%;
$grid-sizes: ( // name: width
    1: 16.66666666667%,
    fourth: 25%,
    third: 33.33333333333%,
    2: 33.33333333333%,
    half: 50%,
    3: 50%,
    two-thirds: 66.666666666667%,
    4: 66.666666666667%,
    three-fourths: 75%
);
$grid-breakpoints: ( // breakpoint, prefix, include offsets (boolean)
    ($bp-xsmall, ".row-start-xsmall", false),
    ($bp-small, ".row-start-small", false),
    ($bp-medium, null, true)
)
```

**_grid.scss**

``` scss
/**
 * @section Grid
 * Structure and layout.
 */

/**
 * Base grid styles: single column
 */
.container {
    max-width: $container-max;
    width: $container-width;
    margin-left: auto;
    margin-right: auto;
}

.row {
    margin-left: $grid-margins * -1;
    margin-right: $grid-margins * -1;
}

%grid-base {
    float: left;
    width: 100%;
    padding-left: $grid-margins;
    padding-right: $grid-margins;
}

@each $grid, $width in ($grid-sizes) {
    .grid-#{$grid} {
        @extend %grid-base;
    }
}


/**
 * Reverses order of grid for content choreography
 */
.grid-flip {
    float: right;
}


/**
 * Add columns to grid on bigger screens
 */
@each $breakpoint, $prefix, $offset in ($grid-breakpoints){
    @media (min-width: $breakpoint) {
        @each $grid, $width in ($grid-sizes) {
            #{$prefix} .grid-#{$grid} {
                width: $width;
            }
        }
        @if $offset {
            @each $grid, $width in ($grid-sizes) {
                #{$prefix} .grid-#{$grid} {
                    margin-left: $width;
                }
            }
        }
    }
}

/**
 * Image gallery
 */
.grid-img {
    @media (min-width: $bp-xsmall)  { width: 50%; }
    @media (min-width: $bp-small) { width: 33.33333333333%; }
    @media (min-width: $bp-medium)  { width: 25%; }
}
```
